tasks:
  - name: Get Composer dependencies for the first time
    init: >
      composer install --ignore-platform-reqs &&
      gp sync-done composer-dependencies

  - name: Setup Sail environment
    init: >
      cp .env.example .env &&
      sed -i "s#APP_URL=http://localhost#APP_URL=$(gp url 80)#g" .env &&
      sed -i "s#GITPOD_VITE_URL=#GITPOD_VITE_URL=$(gp url 5173)#g" .env

  - name: Execute Laravel Sail
    # Fix because of https://github.com/gitpod-io/gitpod/issues/16614
    before: sudo curl -o /usr/local/bin/docker-compose -fsSL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-$(uname -m)
    command: >
      gp sync-await composer-dependencies &&
      ./vendor/bin/sail up -d &&
      ./vendor/bin/sail php artisan key:generate &&
      ./vendor/bin/sail php artisan storage:link &&
      gp sync-done sail-up

  - name: Install Node dependencies and run Vite
    command: >
      gp sync-await sail-up &&
      ./vendor/bin/sail npm install --ignore-scripts  &&
      ./vendor/bin/sail npm run dev

ports:
  - port: 5173
    onOpen: ignore
    visibility: public
    name: Node Server for Vite

# Configure vscode
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - eamodio.gitlens
    - ikappas.composer
    - ms-azuretools.vscode-docker
    - ecmel.vscode-html-css
    - MehediDracula.php-namespace-resolver
    - wmaurer.change-case
    - Equinusocio.vsc-community-material-theme
    - EditorConfig.EditorConfig
    - streetsidesoftware.code-spell-checker
    - rangav.vscode-thunder-client
